name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: "read"

jobs:
  check-code-regeneration:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Regenerate code
        run: nix develop -c go generate ./...

      - name: Ensure the code has been properly regenerated
        run: |
          readonly changed_files="$(git diff --stat)"
          if [[ "${changed_files}" != "" ]]; then
            echo "Found differences after running 'go generate ./...'"
            echo "Please run 'go generate ./...' & commit the changed files:"
            echo "${changed_files}"
            exit 1
          fi

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix develop -c go build -v ./...

      - name: Test
        run: nix develop -c go test -v ./...

  # TODO @dvcorreia: add linting workflow